= Cahier des charges
:doctype: book
:icons: font
:source-highlighter: coderay

== Projet developpement d'application 


|===
| Client: | Bank Univ
| Date: | semaine 24
|===

== Objectif

Le présent document a pour objectif de définir les spécifications et les exigences du projet de développemnt d'application bancaire à partir du code livrée "Daily Bank". Il décrit les fonctionnalités attendues, les contraintes techniques, ainsi que les délais et les ressources nécessaires pour sa réalisation.

== Auteurs

Le cahier des charges a été rédigé par :

- Raban Théo
- Magaz Yahya
- Céolin Thomas

== Révision

|===
| Date | Version 
| [semaine 18] | [Version 1.0] 
|===

[page-break]

== Sommaire

toc::[]














== Introduction du projet
  
Bank Univ souhaite moderniser son système informatique en remplaçant son ancienne application de gestion bancaire. L'application actuelle est obsolète et ne répond plus aux besoins de ses clients ni aux standards de l'industrie bancaire moderne.

Dans le cadre de ce projet, nous avons accès à un code source existant sur lequel nous pouvons nous appuyer pour développer une nouvelle application. L'objectif est de créer une solution plus adaptée aux attentes actuelles de Bank Univ et à celles de ses clients.

Ce cahier des charges est un document de référence qui définit les exigences et les spécifications techniques pour le développement de la nouvelle application. Il est conçu pour guider l'équipe de développement tout au long du processus, en veillant à ce que la nouvelle application réponde efficacement aux besoins de Bank Univ.

== I-Analyse de l'existant
=== 1. Le code livré
=== 2. Contraintes techniques 
=== 3. Contraintes délai
=== 4. Contraintes humaines 


== II- Analyse des nouveaux besoins
=== 1. Technique
=== 2.

== III-Organisation 
=== 1. Modalités d’organisation pour la suite du projet
=== 2. Organisation mise en œuvre dans l’étape CDCU

