= Doc. User

== Sommaire

* [[Contexte]]

== Contexte

Au cours de cette SAE, nous devons d'abord effectuer une V1 du code, puis une V2. Dans la V1 du code, nous avons plusieurs fonctionnalités à implémenter. Tout d'abord, il faudrait une fonction "créer" destinée au chef d'agence, suivie d'une fonction "lire/consulter" également destinée au chef d'agence, puis une fonction "mettre à jour" destinée au chef d'agence, et enfin une fonction "supprimer" destinée au chef d'agence. Ensuite, nous devons créer une fonction "créer" destinée au guichetier, et enfin une fonction "créditer/débiter" destinée au guichetier. Une fois cette première version du code réalisée, nous devons passer à la version 2 dans laquelle d'autres fonctions seront ajoutées, telles qu'une fonction "débit exceptionnel" destinée au chef d'agence, puis une fonction "simuler emprunt" également destinée au chef d'agence, ensuite une fonction "simuler assurance" destinée au chef d'agence, suivie d'une fonction "créer prélèvement" destinée au guichetier, une fonction "lire/consulter prélèvement" destinée au guichetier, une fonction "mettre à jour prélèvement" destinée au guichetier, une fonction "supprimer prélèvement" destinée au guichetier, une fonction "prélèvement automatique" destinée au Batch, et enfin une fonction "relevés mensuels" destinée au Batch.
